import 'package:chinamotorscar/generated/assets.dart';
import 'package:flutter/material.dart';

class Part2QData {
  final int carType;
  final String image;
  final String title;
  final String price;
  final String about;
  final String seats;
  final String horse;
  final String maxspeed;
  final String auto;
  final String mator;
  final String kuzof;
  final String yoqilgi_sarfi;
  final String mator_xajmi;
  final String uzunligi;
  final String kengligi;
  final String balandligi;
  final String gildirak_bazasi;
  final String gildirak_olchami;
  final String yoqilgi_bak_hajmi;

  final String akumlyator_hami;
  final String yurish_masofasi;
  final String elektr_sarfi;

  final int indexx;
  const Part2QData({
    Key? key,
    required this.carType,
    required this.image,
    required this.title,
    required this.price,
    required this.about,
    required this.seats,
    required this.horse,
    required this.maxspeed,
    required this.auto,
    required this.mator,
    required this.kuzof,
    required this.yoqilgi_sarfi,
    required this.mator_xajmi,
    required this.uzunligi,
    required this.kengligi,
    required this.balandligi,
    required this.gildirak_bazasi,
    required this.gildirak_olchami,
    required this.yoqilgi_bak_hajmi,

    required this.akumlyator_hami,
    required this.yurish_masofasi,
    required this.elektr_sarfi,

    required this.indexx,
  });
}

class Part3QData {
  final String image;
  final String title;
  final String price;
  final String about;
  final String sizes;
  final String ozvazni;
  final String yukvazni;
  final String dvigitelModel;
  final String dvigitelHajmi;
  final String yoqilgiBak;
  final String uzatishQutisiModeli;
  final String orqaMost;
  final String gildirakVaShinaOlchami;
  const Part3QData({
    Key? key,
    required this.image,
    required this.title,
    required this.price,
    required this.about,
    required this.sizes,
    required this.ozvazni,
    required this.yukvazni,
    required this.dvigitelModel,
    required this.dvigitelHajmi,
    required this.yoqilgiBak,
    required this.uzatishQutisiModeli,
    required this.orqaMost,
    required this.gildirakVaShinaOlchami,
  });
}
List<Part2QData> part2QData = const [
  Part2QData(
    carType: 1,
    image: Assets.Jac_j7,
    title: "Jac J7",
    price: "253 000 000 so'm",
    about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    seats: "5 Seats",
    horse: "150 h.p",
    maxspeed: "180 km/h",
    auto: "auto",
    mator: "Yevro 5",
    kuzof: "Liftback",
    yoqilgi_sarfi: "100 km - 7.5 L",
    mator_xajmi: "1.5 L turbo",
    uzunligi: "4 772 mm",
    kengligi: "1 820 mm",
    balandligi: "1 492 mm",
    gildirak_bazasi: "2 760 mm",
    gildirak_olchami: "215/50 R17",
    yoqilgi_bak_hajmi: "",

    akumlyator_hami: "",
    yurish_masofasi: "",
    elektr_sarfi: "",

    indexx: 1,
  ),
  Part2QData(
    carType: 1,
    image: Assets.Jac_js6,
    title: "Jac JS6",
    price: "330 000 000 so'm",
    about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    seats: "5 Seats",
    horse: "174 h.p",
    maxspeed: "180 km/h",
    auto: "auto",
    mator: "Yevro 5",
    kuzof: "SUV",
    yoqilgi_sarfi: "100 km - 7.5 L",
    mator_xajmi: "1.5 L turbo",
    uzunligi: "4 605 mm",
    kengligi: "1 890 mm",
    balandligi: "1 700 mm",
    gildirak_bazasi: "2 830 mm",
    gildirak_olchami: "235/55 R18",
    yoqilgi_bak_hajmi: "",

    akumlyator_hami: "",
    yurish_masofasi: "",
    elektr_sarfi: "",

    indexx: 1,
  ),
  Part2QData(
    carType: 1,
    image: Assets.Jac_js8,
    title: "Jac JS8",
    price: "321 000 000 so'm",
    about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    seats: "5 Seats",
    horse: "180 h.p",
    maxspeed: "175 km/h",
    auto: "auto",
    mator: "1.5 L Turbo",
    kuzof: "SUV",
    yoqilgi_sarfi: "100 km - 7.5 L",
    mator_xajmi: "",
    uzunligi: "4815 mm",
    kengligi: "1870 mm",
    balandligi: "1758 mm",
    gildirak_bazasi: "2830 mm",
    gildirak_olchami: "235/50 R19",
    yoqilgi_bak_hajmi: "",

    akumlyator_hami: "",
    yurish_masofasi: "",
    elektr_sarfi: "",

    indexx: 1,
  ),

  Part2QData(
    carType: 1,
    image: Assets.Jac_t8,
    title: "Jac T8 Pickup",
    price: "383 700 000 so'm",
    about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    seats: "5 seats",
    horse: "170 h.p",
    maxspeed: "150 km/h",
    auto: "auto",
    mator: "2.0 L turbo",
    kuzof: "Pickup",
    yoqilgi_sarfi: "100 km - 7.5 L",
    mator_xajmi: "sm3 2378",
    uzunligi: "5325 mm",
    kengligi: "1880 mm",
    balandligi: "1830 mm",
    gildirak_bazasi: "3090 mm",
    gildirak_olchami: "",
    yoqilgi_bak_hajmi: "",

    akumlyator_hami: "",
    yurish_masofasi: "",
    elektr_sarfi: "",

    indexx: 1,
  ),
  Part2QData(
    carType: 1,
    image: Assets.Jac_m3,
    title: "Jac M3 Plus",
    price: "19 500 \$",
    about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    seats: "9 Seats",
    horse: "130 h.p",
    maxspeed: "155 km/h",
    auto: "mexanika",
    mator: "euro 5",
    kuzof: "Minivan",
    yoqilgi_sarfi: "100 km - 8 L",
    mator_xajmi: "1,8 atmosferniy",
    uzunligi: "4661 mm",
    kengligi: "1890 mm",
    balandligi: "1980 mm",
    gildirak_bazasi: "3080 mm",
    gildirak_olchami: "195/65R15",
    yoqilgi_bak_hajmi: "",

    akumlyator_hami: "",
    yurish_masofasi: "",
    elektr_sarfi: "",

    indexx: 1,
  ),
  Part2QData(
    carType: 1,
    image: Assets.Jac_m4,
    title: "Jac M4 Refine",
    price: "23 000 \$",
    about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    seats: "9 Seats",
    horse: "140 h.p",
    maxspeed: "155 km/h",
    auto: "mexanika",
    mator: "",
    kuzof: "Minivan",
    yoqilgi_sarfi: "100 km - 7.5 L",
    mator_xajmi: "sm3 1962",
    uzunligi: "5200 mm",
    kengligi: "1890 mm",
    balandligi: "1980 mm",
    gildirak_bazasi: "3080 mm",
    gildirak_olchami: "215/65 R16",
    yoqilgi_bak_hajmi: "",

    akumlyator_hami: "",
    yurish_masofasi: "",
    elektr_sarfi: "",

    indexx: 1,
  ),
  Part2QData(
    carType: 2,
    image: Assets.Byd_e2,
    title: "BYD SEAGULL",
    price: "17 500 \$",
    about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    seats: "5 seats",
    horse: "75 h.p",
    maxspeed: "170 km/h",
    auto: "Auto",
    mator: "",
    kuzof: "Pickup",
    yoqilgi_sarfi: "",
    mator_xajmi: "",
    uzunligi: "3780 mm",
    kengligi: "1715 mm",
    balandligi: "1540 mm",
    gildirak_bazasi: "2500 mm",
    gildirak_olchami: "",
    yoqilgi_bak_hajmi: "",

    akumlyator_hami: "55 kVt.s",
    yurish_masofasi: "401 km",
    elektr_sarfi: "38.8 kVt/soat",

    indexx: 1,
  ),
  Part2QData(
    carType: 2,
    image: Assets.Byd_Champion,
    title: "BYD CHAMPION",
    price: "\$20 000",
    about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    seats: "5 seats",
    horse: "",
    maxspeed: "175 km/h",
    auto: "auto",
    mator: "",
    kuzof: "Krasover",
    yoqilgi_sarfi: "100 km - 7.5 L",
    mator_xajmi: "",
    uzunligi: "4785 mm",
    kengligi: "1890 mm",
    balandligi: "1660 mm",
    gildirak_bazasi: "2765 mm",
    gildirak_olchami: "215/55 R19",
    yoqilgi_bak_hajmi: "",

    akumlyator_hami: "160 kVt",
    yurish_masofasi: "",
    elektr_sarfi: "87.04 kVt/soat",

    indexx: 1,
  ),
  Part2QData(
    carType: 2,
    image: Assets.Byd_seagull,
    title: "BYD E2",
    price: "19 300 \$",
    about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    seats: "5 seats",
    horse: "95 h.p",
    maxspeed: "160 km/h",
    auto: "auto",
    mator: "",
    kuzof: "Hetchback",
    yoqilgi_sarfi: "100 km - 7.5 L",
    mator_xajmi: "",
    uzunligi: "4240 mm",
    kengligi: "1760 mm",
    balandligi: "1530 mm",
    gildirak_bazasi: "2610 mm",
    gildirak_olchami: "205/60 R16",
    yoqilgi_bak_hajmi: "",

    akumlyator_hami: "55 kVt.s",
    yurish_masofasi: "405 km",
    elektr_sarfi: "43.2 kVt/soat",

    indexx: 1,
  ),
  Part2QData(
    carType: 1,
    image: Assets.gazellenextbusA65R3360,
    title: "Gazel next",
    price: "338 000 000 so'm",
    about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    seats: "16+1 seats",
    horse: "107",
    maxspeed: "130 km/h",
    auto: "mexanika",
    mator: "Evotech A274",
    kuzof: "Avtobus",
    yoqilgi_sarfi: "100 km - 9.8 L",
    mator_xajmi: "2.7",
    uzunligi: "6415 mm",
    kengligi: "2513 mm ",
    balandligi: "2837 mm ",
    gildirak_bazasi: "3745 mm",
    gildirak_olchami: "185/75R16",
    yoqilgi_bak_hajmi: "",

    akumlyator_hami: "",
    yurish_masofasi: "",
    elektr_sarfi: "",

    indexx: 1,
  ),
  Part2QData(
    carType: 1,
    image: Assets.forlanT52400,
    title: "Forland T5 2400",
    price: "182 000 000 so'm",
    about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    seats: "2 seats",
    horse: "102 h.p",
    maxspeed: "150 km/h",
    auto: "mexanika",
    mator: "evro - 5",
    kuzof: "pickup",
    yoqilgi_sarfi: "100 km - ",
    mator_xajmi: "1.8 L",
    uzunligi: "4680 mm",
    kengligi: "1680 mm",
    balandligi: "1920 mm",
    gildirak_bazasi: " 2400 mm",
    gildirak_olchami: "",
    yoqilgi_bak_hajmi: "",

    akumlyator_hami: "",
    yurish_masofasi: "",
    elektr_sarfi: "",

    indexx: 1,
  ),
  Part2QData(
    carType: 1,
    image: Assets.Byd_seagull,
    title: "Forland T5 2600",
    price: "194 000 000 so'm",
    about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    seats: "5 seats",
    horse: "102 h.p",
    maxspeed: "150 km/h",
    auto: "mexanika",
    mator: "evro - 5",
    kuzof: "pickup",
    yoqilgi_sarfi: "100 km - ",
    mator_xajmi: "1.8 L",
    uzunligi: "4925 mm",
    kengligi: "1690 mm",
    balandligi: "1920 mm",
    gildirak_bazasi: " 2600 mm",
    gildirak_olchami: "175/R14",
    yoqilgi_bak_hajmi: "60 L",

    akumlyator_hami: "",
    yurish_masofasi: "",
    elektr_sarfi: "",

    indexx: 1,
  ),
  // Part2QData(
  //   carType: 2,
  //   image: Assets.changenBenBen,
  //   title: "Changan Benben E-Star",
  //   price: "13 800 \$",
  //   about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
  //   seats: "5 Seats",
  //   horse: "p",
  //   maxspeed: "130 km/h",
  //   auto: "auto",
  //   mator: "Hajbuck",
  //   kuzof: "pickup",
  //   yoqilgi_sarfi: "100 km - ",
  //   mator_xajmi: "",
  //   uzunligi: "377 mm",
  //   kengligi: "1650 mm",
  //   balandligi: "1570 mm",
  //   gildirak_bazasi: "2410 mm",
  //   gildirak_olchami: "175/ 60 R15",
  //   yoqilgi_bak_hajmi: "60 L",
  //
  //   akumlyator_hami: "55 kVt",
  //   yurish_masofasi: "301 km",
  //   elektr_sarfi: "32.2 kVt/soat",
  //
  //   indexx: 1,
  // ),
];

List<Part3QData> part3QData = const [
  Part3QData(
    image: Assets.avtotoplizapravshik1,
    title: "Faw JK6 CA1250",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "9800×2460×2780",
    ozvazni: "11 000 KG",
    yukvazni: "20 000 KG",
    dvigitelModel: "FAW CA6DLD-26E5",
    dvigitelHajmi: "6.6 L",
    yoqilgiBak: "400 L",
    uzatishQutisiModeli: "FAST 8JS125TA",
    orqaMost: "11 тонн ABS",
    gildirakVaShinaOlchami: "12R22.5-16PR",
  ),
  Part3QData(
    image: Assets.avtotoplizapravshik44,
    title: "FAW JK6 CA1250",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "9800×2460×2780",


    ozvazni: "11 000 KG",
    yukvazni: "20 000 KG",
    dvigitelModel: "FAW CA6DLD-26E5",
    dvigitelHajmi: "6.6 L",
    yoqilgiBak: "400 L",
    uzatishQutisiModeli: "FAST 8JS125TA",
    orqaMost: "11 тонн ABS",
    gildirakVaShinaOlchami: "12R22.5-16PR",
  ),
  Part3QData(
    image: Assets.avtotoplizapravshik22,
    title: "FAW JK6 CA1250",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "11000×2460×2780",
    ozvazni: "13 000 KG",
    yukvazni: "20 000 KG",
    dvigitelModel: "FAW CA6DLD-26E5",
    dvigitelHajmi: "6.6 L",
    yoqilgiBak: "400 L",
    uzatishQutisiModeli: "FAST 8JS125TA",
    orqaMost: "11 тонн ABS",
    gildirakVaShinaOlchami: "12R22.5-16PR",
  ),
  Part3QData(
    image: Assets.faw1,
    title: "Faw J7",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "6270×2550×4000",
    ozvazni: "18 000 KG",
    yukvazni: "42 000 KG",
    dvigitelModel: "Xichai CA6DM3-55E52",
    dvigitelHajmi: "12.52 L",
    yoqilgiBak: "550 L",
    uzatishQutisiModeli: "ZF-12TX2621TD",
    orqaMost: "",
    gildirakVaShinaOlchami: "",
  ),

  Part3QData(
    image: Assets.faw2,
    title: "FAW J6P",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "7400×2550×3980",
    ozvazni: "25 000 KG",
    yukvazni: " 75 000 KG",
    dvigitelModel: "FAW CA6SM3-47EN",
    dvigitelHajmi: "12.5 L",
    yoqilgiBak: "470 L",
    uzatishQutisiModeli: "CA12TAX210M",
    orqaMost: "",
    gildirakVaShinaOlchami: "315/70R22.5 18 PR",
  ),Part3QData(
    image: Assets.faw3,
    title: "FAW JH6",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "6120×2550×3910",
    ozvazni: "18 000 KG",
    yukvazni: "42 000 KG",
    dvigitelModel: "Weichai WP10H400E50",
    dvigitelHajmi: "9.5 L",
    yoqilgiBak: "400 L",
    uzatishQutisiModeli: "Shaanxi C12JSDQXL200TA",
    orqaMost: "",
    gildirakVaShinaOlchami: "12R22.5-18PR",
  ),Part3QData(
    image: Assets.faw4,
    title: "FAW JH6",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "6120×2550×3910",
    ozvazni: "18 000 KG",
    yukvazni: "42 000 KG",
    dvigitelModel: "Weichai WP13NG430E52",
    dvigitelHajmi: "12.5 L",
    yoqilgiBak: "430 L",
    uzatishQutisiModeli: "C12JSDQXL220TA",
    orqaMost: "",
    gildirakVaShinaOlchami: "315/70R22.5",
  ),Part3QData(
    image: Assets.faw5,
    title: "FAW JK6",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "6000×2460×2780",
    ozvazni: "10 000 KG",
    yukvazni: "25 000 KG",
    dvigitelModel: "Xichai CA6DLD-26E5",
    dvigitelHajmi: "6.5 L",
    yoqilgiBak: "260 L",
    uzatishQutisiModeli: "8JS125TA",
    orqaMost: "",
    gildirakVaShinaOlchami: "12R22.5-16",
  ),Part3QData(
    image: Assets.faw6,
    title: "FAW JH6",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "7645×2550×3325",
    ozvazni: "10 880 KG",
    yukvazni: "25 000 KG",
    dvigitelModel: "Xichai CA6DM2-39E52",
    dvigitelHajmi: "11,05 L",
    yoqilgiBak: "390 L",
    uzatishQutisiModeli: "12JSD200T-B",
    orqaMost: "",
    gildirakVaShinaOlchami: "12.00R20 18PR",
  ),Part3QData(
    image: Assets.faw7,
    title: "FAW J6L",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "10610×2550×3500",
    ozvazni: "28 200 KG",
    yukvazni: "18 000 KG",
    dvigitelModel: "Xichai CA6DH1-24E5",
    dvigitelHajmi: "6 L",
    yoqilgiBak: "240 L",
    uzatishQutisiModeli: "CA8TAX100FS",
    orqaMost: "",
    gildirakVaShinaOlchami: "12R22.5-18PR",
  ),Part3QData(
    image: Assets.faw8,
    title: "FAW JK6",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "9800×2550×3860",
    ozvazni: "28 000 KG",
    yukvazni: "18 000 KG",
    dvigitelModel: "FAW CA6DLD-26E5",
    dvigitelHajmi: "6.6 L",
    yoqilgiBak: "260 L",
    uzatishQutisiModeli: "FAST 8JS125TA",
    orqaMost: "",
    gildirakVaShinaOlchami: "12R22.5-16PR",
  ),Part3QData(
    image: Assets.faw9,
    title: "FAW JK6",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "9100×2460×2780",
    ozvazni: "28 000 KG",
    yukvazni: "18 000 KG",
    dvigitelModel: "Xichai CA6DLD-26E5",
    dvigitelHajmi: "6.6 L",
    yoqilgiBak: "260 L",
    uzatishQutisiModeli: "8JS125TA",
    orqaMost: "",
    gildirakVaShinaOlchami: "12R22.5-16",
  ),Part3QData(
    image: Assets.faw10,
    title: "FAW JK6",
    price: "\$20 000",
    about: "1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    sizes: "9500×2500×3180",
    ozvazni: "28 000 KG",
    yukvazni: "18 000 KG",
    dvigitelModel: "Xichai CA6DLD-26E5",
    dvigitelHajmi: "6.6 L",
    yoqilgiBak: "260 L",
    uzatishQutisiModeli: "8JS125TA",
    orqaMost: "",
    gildirakVaShinaOlchami: "12R22.5-16",
  ),
];
